version: '3'

services:
  audit:
    build:
      context: .
    environment:
      BROWSERLESS_ENDPOINT: 'http://browserless:3000?headless=false'
      AUDIT_URL: ${AUDIT_URL:-https://www.browserless.io/}
    volumes:
      - './index.js:/usr/src/app/index.js:ro'
      - './lib:/usr/src/app/lib:ro'
    depends_on:
      - browserless

  browserless:
    image: browserless/chrome
    environment:
      FUNCTION_EXTERNALS: '["lighthouse"]'
      KEEP_ALIVE: 'false'
      PORT: 3000
      PREBOOT_CHROME: 'true'
    shm_size: 1gb
